#!/bin/bash

#####################################################################################
#This script runs at boot to create and set the default screen resolution		                 
#to whichever you wish. I won't be responsible for ANY crash, broken monitor,  		 
#thermal implosion, radioactive blast, CPU reks, BSODs even in a GNU/Linux box or     
#whatever damage caused to your computer. Be brave and/or ready to run.	       	         
#															                                         
#Engineered by xVlaze, 2016.												 
#####################################################################################  

read -p 'Enter your horizontal screen resolution: ' RESX
read -p 'Enter your vertical screen resolution: ' RESY
read -p 'Enter your image output (e.g. VGA1): ' OUTPUT

MODELINE=$(cvt $RESX $RESY | awk '/Modeline/' | cut -d' ' -f2-)
RESNAME=$(cvt $RESX $RESY | awk '/Modeline/' | cut -d' ' -f2-3)

xrandr --newmode $MODELINE
xrandr --addmode $OUTPUT $RESNAME

